server:
  port: 80
spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: RM99632
    password: 230605
  jpa:
    generate-ddl: true
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.Oracle10gDialect